{                Pascal Validation Suite  Version 5.7                }
{                                                                    }
{          (C) Copyright 1982, British Standards Institution         }
{                                                                    }
{ TEST 6.10-4, FILE=DEV254, CLASS=DEVIANCE, LEVEL=0                  }
{                                                                    }
{:This program deviates since two of the program-parameters are      }
{:identical.                                                         }
{                                                                    }
{ Modification History :                                             }
{   V3.0: New test.                                                  }
{   V5.2: File header comments reformatted and file name added to    }
{         TEST line and output lines.                                }
{                                                                    }

program DEV254(output,input,output);
begin
   writeln(' DEVIATES...6.10-4 (DEV254)')
end.
