{                Pascal Validation Suite  Version 5.7                }
{                                                                    }
{          (C) Copyright 1982, British Standards Institution         }
{                                                                    }
{ TEST 6.1.7-17, FILE=DEV262, CLASS=DEVIANCE, LEVEL=0                }
{                                                                    }
{:A string in Pascal contains at least one character. Hence this     }
{:program deviates from the Standard.                                }
{                                                                    }
{ Modification History :                                             }
{   V5.2: New test suggested by Brian Wichmann.                      }
{                                                                    }

program DEV262(output);

begin
  writeln('');
  writeln(' DEVIATES...6.1.7-17 (DEV262)')
end.
