{                Pascal Validation Suite  Version 5.7                }
{                                                                    }
{          (C) Copyright 1982, British Standards Institution         }
{                                                                    }
{ PRETEST 6.6.5.2-11, FILE=ERR25P, CLASS=ERRORHANDLING, LEVEL=0,     }
{ NUMBER=15                                                          }
{                                                                    }
{ Modification History :                                             }
{   V5.2: File header comments reformatted and file name added to    }
{         TEST line and output lines.                                }
{                                                                    }

program ERR25P(output);
var
   f : file of char;
begin
   writeln(' PRETEST...6.6.5.2-11 (ERR25P)')
end.
